### PR TITLE
some enhancements

### PR DESCRIPTION
**Pull request by cytec**
* use pkg-config to get LDFLAGS 
* Renamed VideoCodec to VideoCodecName for better recognition (sorry for the trouble)
* Added AudioCodec and AudioCodecName
* Export the Bitrate value

### CODE REVIEW

**Comment by opennota** [comment]
I think something like VideoCodecLong or VideoCodecLongName would be a better name.

**Comment by cytec** [comment]
i'd go with VideoCodecLongName and AudioCodecLongName then...

**Comment by opennota** [comment]
Ok. If you update your PR with `push -f` I'll merge it.

**Comment by cytec** [comment]
updated

**Pull request merged**
